id: D8DDD8BDD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T13:58:40+00:00'
last_modified: '2022-05-30T06:18:43.032027+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '2278':
      image_group_id: I1PD95959
      title: སྤོས་ཀྱི་སྦྱོར་བ་རེའུ་ཆར་བྱས་པ།
      total_pages: 1872
      order: 114
      base_file: 2278.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
