id: P38733634
initial_creation_type: ocr
source_metadata:
  volumes:
    0655b4d83ec74a35abd99c47d7a31bc4:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: སྤོས་ཀྱི་སྦྱོར་བ་རེའུ་ཆར་བྱས་པ།
      total_pages: 1872
      volume_number: 114
